import React from "react";
import {
  Activity,
  Apple,
  Baby,
  BaggageClaim,
  Banknote,
  Bath,
  BedDouble,
  Beer,
  Bike,
  BookOpen,
  BriefcaseBusiness,
  Bus,
  CakeSlice,
  Calculator,
  Camera,
  Car,
  CarTaxiFront,
  Cat,
  CircleEllipsis,
  Coffee,
  Coins,
  Dog,
  Droplets,
  Dumbbell,
  Film,
  Flame,
  Flower2,
  Fuel,
  Gamepad2,
  Gem,
  Gift,
  GraduationCap,
  Headphones,
  Heart,
  HeartPulse,
  Hospital,
  House,
  IceCreamBowl,
  Lamp,
  Landmark,
  Leaf,
  Library,
  MapPin,
  Music,
  Package,
  PawPrint,
  Pencil,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Receipt,
  Sandwich,
  Scissors,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Soup,
  Sparkles,
  Stethoscope,
  Store,
  Tag,
  Ticket,
  TrainFront,
  TramFront,
  Trees,
  Umbrella,
  Utensils,
  WalletCards,
  WashingMachine,
  Wifi,
  Wine,
  Wrench,
  Zap
} from "lucide-react";

export const categoryIconGroups = [
  { id: "all", name: "全部" },
  { id: "food", name: "餐饮" },
  { id: "transport", name: "出行" },
  { id: "home", name: "居家" },
  { id: "shopping", name: "购物" },
  { id: "health", name: "健康" },
  { id: "study", name: "学习" },
  { id: "fun", name: "娱乐" },
  { id: "finance", name: "财务" },
  { id: "life", name: "生活" }
];

export const categoryIconOptions = [
  { id: "food", name: "餐饮", group: "food", Icon: Utensils, keywords: "吃饭 餐厅" },
  { id: "coffee", name: "咖啡", group: "food", Icon: Coffee, keywords: "饮品 奶茶" },
  { id: "cake", name: "蛋糕", group: "food", Icon: CakeSlice, keywords: "甜品 生日" },
  { id: "ice-cream", name: "冰淇淋", group: "food", Icon: IceCreamBowl, keywords: "甜品 冷饮" },
  { id: "soup", name: "汤面", group: "food", Icon: Soup, keywords: "面条 汤" },
  { id: "pizza", name: "披萨", group: "food", Icon: Pizza, keywords: "西餐" },
  { id: "sandwich", name: "简餐", group: "food", Icon: Sandwich, keywords: "早餐 汉堡" },
  { id: "fruit", name: "水果", group: "food", Icon: Apple, keywords: "生鲜 苹果" },
  { id: "beer", name: "啤酒", group: "food", Icon: Beer, keywords: "酒吧 饮酒" },
  { id: "wine", name: "酒水", group: "food", Icon: Wine, keywords: "红酒" },

  { id: "transport", name: "汽车", group: "transport", Icon: Car, keywords: "开车 车辆" },
  { id: "taxi", name: "打车", group: "transport", Icon: CarTaxiFront, keywords: "出租车 滴滴" },
  { id: "bus", name: "公交", group: "transport", Icon: Bus, keywords: "巴士" },
  { id: "train", name: "火车", group: "transport", Icon: TrainFront, keywords: "高铁 铁路" },
  { id: "subway", name: "地铁", group: "transport", Icon: TramFront, keywords: "轨道交通" },
  { id: "plane", name: "飞机", group: "transport", Icon: Plane, keywords: "机票 航空" },
  { id: "bike", name: "骑行", group: "transport", Icon: Bike, keywords: "自行车" },
  { id: "ship", name: "轮船", group: "transport", Icon: Ship, keywords: "船票" },
  { id: "fuel", name: "加油", group: "transport", Icon: Fuel, keywords: "汽油 充电" },
  { id: "travel", name: "旅行", group: "transport", Icon: BaggageClaim, keywords: "行李 出游" },
  { id: "location", name: "地点", group: "transport", Icon: MapPin, keywords: "位置 停车" },

  { id: "home", name: "居家", group: "home", Icon: House, keywords: "房屋 家庭" },
  { id: "water", name: "用水", group: "home", Icon: Droplets, keywords: "水费 自来水" },
  { id: "electricity", name: "用电", group: "home", Icon: Zap, keywords: "电费 充电" },
  { id: "gas", name: "燃气", group: "home", Icon: Flame, keywords: "煤气 天然气" },
  { id: "wifi", name: "网络", group: "home", Icon: Wifi, keywords: "宽带 网费" },
  { id: "phone", name: "话费", group: "home", Icon: Smartphone, keywords: "手机 通讯" },
  { id: "bed", name: "住宿", group: "home", Icon: BedDouble, keywords: "酒店 房租" },
  { id: "bath", name: "洗浴", group: "home", Icon: Bath, keywords: "浴室" },
  { id: "laundry", name: "洗衣", group: "home", Icon: WashingMachine, keywords: "洗衣机 干洗" },
  { id: "lamp", name: "家居", group: "home", Icon: Lamp, keywords: "家具 装修" },
  { id: "repair", name: "维修", group: "home", Icon: Wrench, keywords: "修理 工具" },

  { id: "shopping", name: "购物", group: "shopping", Icon: ShoppingBag, keywords: "买东西" },
  { id: "cart", name: "超市", group: "shopping", Icon: ShoppingCart, keywords: "商超 买菜" },
  { id: "clothes", name: "服饰", group: "shopping", Icon: Shirt, keywords: "衣服 穿搭" },
  { id: "package", name: "快递", group: "shopping", Icon: Package, keywords: "网购 包裹" },
  { id: "jewelry", name: "珠宝", group: "shopping", Icon: Gem, keywords: "首饰" },
  { id: "store", name: "商店", group: "shopping", Icon: Store, keywords: "门店 商场" },
  { id: "gift", name: "礼物", group: "shopping", Icon: Gift, keywords: "送礼 红包" },

  { id: "health", name: "健康", group: "health", Icon: HeartPulse, keywords: "医疗 身体" },
  { id: "medicine", name: "药品", group: "health", Icon: Pill, keywords: "买药 药店" },
  { id: "hospital", name: "医院", group: "health", Icon: Hospital, keywords: "门诊 住院" },
  { id: "doctor", name: "医生", group: "health", Icon: Stethoscope, keywords: "诊所 看病" },
  { id: "fitness", name: "健身", group: "health", Icon: Dumbbell, keywords: "运动 健身房" },
  { id: "activity", name: "运动", group: "health", Icon: Activity, keywords: "锻炼 跑步" },
  { id: "heart", name: "爱心", group: "health", Icon: Heart, keywords: "关怀 公益" },

  { id: "study", name: "学习", group: "study", Icon: BookOpen, keywords: "读书 课程" },
  { id: "school", name: "教育", group: "study", Icon: GraduationCap, keywords: "学校 学费" },
  { id: "stationery", name: "文具", group: "study", Icon: Pencil, keywords: "笔 纸" },
  { id: "library", name: "图书馆", group: "study", Icon: Library, keywords: "借书" },
  { id: "calculator", name: "计算", group: "study", Icon: Calculator, keywords: "数学 工具" },

  { id: "fun", name: "游戏", group: "fun", Icon: Gamepad2, keywords: "娱乐 手游" },
  { id: "movie", name: "电影", group: "fun", Icon: Film, keywords: "影院 视频" },
  { id: "music", name: "音乐", group: "fun", Icon: Music, keywords: "演出 唱歌" },
  { id: "headphones", name: "音频", group: "fun", Icon: Headphones, keywords: "耳机 会员" },
  { id: "camera", name: "摄影", group: "fun", Icon: Camera, keywords: "照片 相机" },
  { id: "ticket", name: "票务", group: "fun", Icon: Ticket, keywords: "门票 演唱会" },

  { id: "wallet", name: "钱包", group: "finance", Icon: WalletCards, keywords: "银行卡 支付" },
  { id: "cash", name: "现金", group: "finance", Icon: Banknote, keywords: "纸币" },
  { id: "saving", name: "储蓄", group: "finance", Icon: PiggyBank, keywords: "存钱" },
  { id: "bank", name: "银行", group: "finance", Icon: Landmark, keywords: "账户" },
  { id: "work", name: "工作", group: "finance", Icon: BriefcaseBusiness, keywords: "工资 办公" },
  { id: "receipt", name: "账单", group: "finance", Icon: Receipt, keywords: "发票 报销" },
  { id: "coins", name: "零钱", group: "finance", Icon: Coins, keywords: "硬币 收益" },

  { id: "baby", name: "母婴", group: "life", Icon: Baby, keywords: "儿童 宝宝" },
  { id: "pet", name: "宠物", group: "life", Icon: PawPrint, keywords: "猫 狗" },
  { id: "cat", name: "猫咪", group: "life", Icon: Cat, keywords: "猫粮" },
  { id: "dog", name: "狗狗", group: "life", Icon: Dog, keywords: "狗粮" },
  { id: "flower", name: "鲜花", group: "life", Icon: Flower2, keywords: "花店 植物" },
  { id: "beauty", name: "美容", group: "life", Icon: Sparkles, keywords: "护肤 化妆" },
  { id: "haircut", name: "理发", group: "life", Icon: Scissors, keywords: "美发" },
  { id: "umbrella", name: "保险", group: "life", Icon: Umbrella, keywords: "保障" },
  { id: "leaf", name: "环保", group: "life", Icon: Leaf, keywords: "绿色" },
  { id: "outdoors", name: "户外", group: "life", Icon: Trees, keywords: "露营 公园" },
  { id: "tag", name: "标签", group: "life", Icon: Tag, keywords: "分类" },
  { id: "other", name: "其他", group: "life", Icon: CircleEllipsis, keywords: "更多 默认" }
];

const iconMap = new Map(categoryIconOptions.map((option) => [option.id, option.Icon]));

export function CategoryIcon({ name = "other", size = 20, ...props }) {
  const Icon = iconMap.get(name) || CircleEllipsis;
  return <Icon size={size} strokeWidth={2.05} aria-hidden="true" {...props} />;
}

export function searchCategoryIcons(query, group = "all") {
  const keyword = String(query || "").trim().toLocaleLowerCase();
  return categoryIconOptions.filter((option) => {
    if (group !== "all" && option.group !== group) return false;
    if (!keyword) return true;
    return `${option.name} ${option.id} ${option.keywords}`.toLocaleLowerCase().includes(keyword);
  });
}
